<?php
//$Id
/**
 * genera lista de ponencias para una sesión
 */
 
function custom_node_view($node, $build_mode = 'full') {
if ($node->type == 'sesion') {
		$sql = "SELECT entity_id FROM {field_data_field_sesiones} WHERE field_sesiones_nid = :uid";
		$result = db_query($sql, array(':uid' => $node->nid));
		if (!empty($ponencias)) {
		foreach ($result as $record) {
			$nid = $record->entity_id;
			$node_sesion = node_load($nid);
		  $link = l($node_sesion->title, 'node/' . $node_sesion->nid);
			$ponencias[] = $link;	
  	}
		
			$node->content['ponencias'] = array(
				'#markup' => '<strong>Ponencias</strong>' . theme('item_list', array('items' => $ponencias)),
				'#weight' => 100,
			);
		}
	}
}  
